# Usar a imagem base do Node.js
FROM node:18

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos de configuração do projeto
COPY frontend/webapp/package*.json ./

# Instalar as dependências
RUN npm install --production

# Copiar o restante dos arquivos do frontend
COPY frontend/webapp/ .

# Construir a aplicação
RUN npm run build

# Expor a porta que a aplicação irá rodar
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
