services:
  db:
    image: postgres:17.3
    container_name: projeto-final-db
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: projeto-final-api
    environment:
      POSTGRES_PASSWORD: minhasenha
    depends_on:
      - db
    ports:
      - "5064:5064"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: projeto-final-frontend
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
