services:
  # Infrastructure
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
    networks:
      - test-docker-sample-net

  # Development API
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    container_name: api-dev
    depends_on:
      - db
    ports:
      - "5064:5064"
    volumes:
      - ./backend/src:/api
    networks:
      - test-docker-sample-net
    environment:
      PG_CONNECTION_STRING: "postgresql://meuusuario:minhasenha@db:5432/meubanco"
    tty: true
    stdin_open: true
    command: ["/bin/sh", "-c", "/wait-for-postgres.sh db && dotnet watch run --project /api/Api/Api.csproj"]


  # Development Web
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.web.dev
    container_name: web-dev
    tty: true
    stdin_open: true
    command: ["nginx", "-g", "daemon off;"]  # Iniciar o Nginx
    ports:
      - "8080:80"
    depends_on:
      - api-dev
    volumes:
      - ./frontend/webapp/wwwroot:/usr/share/nginx/html  # Mapeando o diretório correto
    networks:
      - test-docker-sample-net

networks:
  test-docker-sample-net:
    driver: bridge
