# Usar a imagem base do Nginx
FROM nginx:alpine

# Definir o diretório de trabalho
WORKDIR /web

# Expor a porta 80
EXPOSE 80

# Remover arquivos padrão do Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copiar os arquivos do frontend para o diretório do Nginx
COPY ./frontend/webapp/wwwroot/html /usr/share/nginx/html

# Listar permissões dos arquivos
RUN ls -l /usr/share/nginx/html

# Copiar o arquivo de configuração do Nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
