FROM postgres:latest

# Definir variáveis de ambiente para o PostgreSQL
ENV POSTGRES_USER=meuusuario
ENV POSTGRES_PASSWORD=minhasenha
ENV POSTGRES_DB=meubanco

# Copiar scripts de inicialização (se houver)
# COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
